Parcelrate/Models/AddressViewModel.cs
using System.ComponentModel.DataAnnotations;
using ParcelrateUtilities;

namespace Parcelrate.Models
{
    public class AddressViewModel
    {
        public long Id { get; set; }
        [Required(ErrorMessageResourceName = "Required_CustomerID", ErrorMessageResourceType = typeof(ParcelrateResources.Resources))]
        public string CustomerID { get; set; }
        public string FirstName { get; set; }
        [Required(ErrorMessageResourceName = "Required_LastName", ErrorMessageResourceType = typeof(ParcelrateResources.Resources))]
        public string LastName { get; set; }
        [Required(ErrorMessageResourceName = "Required_Street", ErrorMessageResourceType = typeof(ParcelrateResources.Resources))]
        public string Address1 { get; set; }
        [Required(ErrorMessageResourceName = "Required_HouseNumber", ErrorMessageResourceType = typeof(ParcelrateResources.Resources))]
        [MaxLength(7, ErrorMessageResourceName = "Address_Length", ErrorMessageResourceType = typeof(ParcelrateResources.Resources))]
        public string Address2 { get; set; }
        public string Company { get; set; }
        [Required(ErrorMessageResourceName = "Required_City", ErrorMessageResourceType = typeof(ParcelrateResources.Resources))]
        public string City { get; set; }
        [Required(ErrorMessageResourceName = "Required_PostalCode", ErrorMessageResourceType = typeof(ParcelrateResources.Resources))]
        public string PostalCode { get; set; }
        [Required(ErrorMessageResourceName = "Required_PhoneNo", ErrorMessageResourceType = typeof(ParcelrateResources.Resources))]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(Constants.DigitValidationRegex, ErrorMessageResourceName = "Valid_Phone_No", ErrorMessageResourceType = typeof(ParcelrateResources.Resources))]
        public string PhoneNo { get; set; }
        [Required(ErrorMessageResourceName = "Required_Email", ErrorMessageResourceType = typeof(ParcelrateResources.Resources))]
        [EmailAddress(ErrorMessageResourceName = "Valid_Email", ErrorMessageResourceType = typeof(ParcelrateResources.Resources))]
        public string Email { get; set; }
        [Required(ErrorMessageResourceName = "Required_Country", ErrorMessageResourceType = typeof(ParcelrateResources.Resources))]
        public long? CountryId { get; set; }
        public string CountryCode { get; set; }
        public string PhonePrefix { get; set; }
        public bool IsDefault { get; set; }
        public bool IsPickupOrder { get; set; }
    }
}

Parcelrate/Controllers/AddressController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Logging;
using Microsoft.Net.Http.Headers;
using Parcelrate.Helpers;
using Parcelrate.Models;
using ParcelrateComponent.Interfaces;
using ParcelrateEntities;
using ParcelrateUtilities;
using ReflectionIT.Mvc.Paging;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Parcelrate.Controllers
{
    [CustomAuthorize]
    public class AddressController : Controller
    {
        private readonly IAddressComponent _addressComponent;
        private readonly ICountryComponent _countryComponent;
        private readonly IUserComponent _userComponent;
        private readonly IMapper _mapper;
        private readonly Common _common;
        private readonly ILogger<AddressController> _logger;


        public AddressController(IMapper mapper, Common common, IAddressComponent addressBAL, ICountryComponent countryBAL, IUserComponent userBAL, ILogger<AddressController> logger)
        {
            _mapper = mapper;
            _common = common;
            _addressComponent = addressBAL;
            _countryComponent = countryBAL;
            _userComponent = userBAL;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string filter, int page = 1, string sortExpression = Constants.AddressDefaultSortExpression)
        {
            var user = _userComponent.GetUserByUsername(User.Identity.Name);
            var qry = _addressComponent.GetAddressesQuery(user.ID);
            ViewData[Constants.Filter] = filter;
            if (!string.IsNullOrEmpty(filter) && !string.IsNullOrWhiteSpace(filter))
                qry = qry.Where(a => a.FirstName != null && a.FirstName.ToLower().Contains(filter.Trim()) ||
                    a.LastName != null && a.LastName.ToLower().Contains(filter.Trim()) ||
                    (a.FirstName + " " + a.LastName).Contains(new Regex(@"\s\s+").Replace(filter.Trim(), " ")));
            var model = await PagingList.CreateAsync(qry, Constants.PageSize, page, sortExpression, Constants.AddressDefaultSortExpression);
            model.RouteValue = new RouteValueDictionary {{ Constants.Filter, filter}};
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            try
            {
                string culture = Convert.ToString(User.Claims.FirstOrDefault(x => x.Type == Constants.Culture)?.Value);
                ViewBag.CountryList = _countryComponent.GetCountries(culture);
            }
            catch (Exception ex)
            {
                _logger.LogError(StaticFunctions.LogErrorMessage(nameof(AddressController), nameof(Create), ex));
            }
            return View(new AddressViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AddressViewModel addressViewModel)
        {
            try
            {
                string culture = Convert.ToString(User.Claims.FirstOrDefault(x => x.Type == Constants.Culture)?.Value);
                ViewBag.CountryList = _countryComponent.GetCountries(culture);
                if (ModelState.IsValid)
                {
                    addressViewModel.CustomerID = addressViewModel.CustomerID.Trim();
                    var address = _mapper.Map<AddressViewModel, AddressEntity>(addressViewModel);
                    var user = _userComponent.GetUserByUsername(User.Identity.Name);
                    if (_addressComponent.AddAddress(address, user.ID) < 0)
                        ViewBag.ErrorMessage = ParcelrateResources.Resources.CustomerID_AlreadyExist_Error;
                    else
                        ViewBag.IsSuccess = true;
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ParcelrateResources.Resources.ErrorMessage);
                _logger.LogError(StaticFunctions.LogErrorMessage(nameof(AddressController), nameof(Create), ex));
            }
            return View(addressViewModel);
        }

        [HttpGet]
        public IActionResult Edit(long? id)
        {
            string culture = Convert.ToString(User.Claims.FirstOrDefault(x => x.Type == Constants.Culture)?.Value);
            ViewBag.CountryList = _countryComponent.GetCountries(culture);
            if (id == null)
                return NotFound();
            var address = _addressComponent.GetAddressByID((long)id);
            var addressModel = _mapper.Map<AddressEntity, AddressViewModel>(address);
            return View(addressModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(long id, AddressViewModel addressViewModel)
        {
            try
            {
                string culture = Convert.ToString(User.Claims.FirstOrDefault(x => x.Type == Constants.Culture)?.Value);
                ViewBag.CountryList = _countryComponent.GetCountries(culture);
                if (id != addressViewModel.Id)
                    return NotFound();
                if (addressViewModel.IsDefault)
                    ModelState.Remove(nameof(addressViewModel.CustomerID));
                if (ModelState.IsValid)
                {
                    if (!addressViewModel.IsDefault)
                        addressViewModel.CustomerID = addressViewModel.CustomerID.Trim();
                    var address = _mapper.Map<AddressViewModel, AddressEntity>(addressViewModel);
                    var user = _userComponent.GetUserByUsername(User.Identity.Name);
                    if (_addressComponent.AddAddress(address, user.ID) < 0)
                        ViewBag.ErrorMessage = ParcelrateResources.Resources.CustomerID_AlreadyExist_Error;
                    else
                        ViewBag.IsSuccess = true;
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ParcelrateResources.Resources.ErrorMessage);
                _logger.LogError(StaticFunctions.LogErrorMessage(nameof(AddressController), nameof(Edit), ex));
            }
            return View(addressViewModel);
        }

        [HttpPost]
        public IActionResult Delete(long id)
        {
            try
            {
                _addressComponent.DeleteAddress(id);
                return Json(new { IsSuccess = true, message = ParcelrateResources.Resources.Address_Deleted });
            }
            catch (Exception ex)
            {
                _logger.LogError(StaticFunctions.LogErrorMessage(nameof(AddressController), nameof(Delete), ex));
                return Json(new { IsSuccess = false, error = ParcelrateResources.Resources.DeleteAddress_Error });
            }
        }

        [HttpPost]
        public IActionResult DownloadSampleCSV()
        {
            try
            {
                string filePath = _common.GetWebRootPath() + Constants.TemplateFolder + Constants.SampleCSVFileName;
                if (System.IO.File.Exists(filePath))
                    return Json(new { IsSuccess = true, Url = Url.Action(nameof(AddressController.DownloadCSV), new { filePath }) });
            }
            catch (Exception ex)
            {
                _logger.LogError(StaticFunctions.LogErrorMessage(nameof(AddressController), nameof(DownloadSampleCSV), ex));
            }
            return Json(new { IsSuccess = false, error = ParcelrateResources.Resources.SampleCSV_NotExist });
        }

        [HttpGet]
        public IActionResult DownloadCSV(string filePath)
        {
            var contentDisposition = new ContentDispositionHeaderValue("attachment");
            contentDisposition.SetHttpFileName(Constants.SampleCSVFileName);
            Response.Headers[HeaderNames.ContentDisposition] = contentDisposition.ToString();
            return File(System.IO.File.OpenRead(filePath), "text/csv", Constants.SampleCSVFileName);
        }

        [HttpPost]
        public IActionResult UploadFile(IFormFile file)
        {
            DataTable validAddressess = new DataTable();
            string errorMessage = string.Empty;
            DataTable uploadAddressess = null;
            try
            {
                if (file != null && file.Length > 0 && Path.GetExtension(file.FileName) == Constants.CsvFileExtension)
                {
                    uploadAddressess = StaticFunctions.ReadCsvFile(file.OpenReadStream());
                    ValidateUploadedFile(uploadAddressess, out errorMessage, out validAddressess);
                    if (validAddressess.Rows.Count > 0)
                    {
                        var user = _userComponent.GetUserByUsername(User.Identity.Name);
                        bool isSuccess = _addressComponent.AddAddressesFromDataTable(validAddressess, user.ID);
                        if (isSuccess)
                        {
                            if (errorMessage != string.Empty)
                            {
                                errorMessage = validAddressess.Rows.Count + " " + ParcelrateResources.Resources.Address_Imported +
                                    Environment.NewLine + Environment.NewLine +
                                    ParcelrateResources.Resources.Error_Detail_Heading +
                                    Environment.NewLine + Environment.NewLine +
                                    errorMessage;
                            }
                            return Json(new { IsSuccess = true, message = ParcelrateResources.Resources.Address_Imported, errorMessages = errorMessage });
                        }
                    }
                }
                if (errorMessage != string.Empty)
                {

Parcelrate/Views/Address/Create.cshtml
@model Parcelrate.Models.AddressViewModel
@using ParcelrateUtilities
@{
    ViewData["Title"] = ParcelrateResources.Resources.Add_Address;
    ViewBag.CurrentPage = "Addresses";
}
<div class="con-padding shipmant-heading">
    <div class="col-md-12">
        <h1>@ParcelrateResources.Resources.Add_Address</h1>
        <a onclick="getHasChanges();" class="back-link"><img src="~/images/back-btn.png" alt="back-link" />@ParcelrateResources.Resources.Back</a>
    </div>
</div>
<div class="upload-content text-center">
    <div class="image-upload">
        <label for="file-input">
            <div class="upload-icon" style="cursor:pointer;" onclick="SelectFile();">
                <img src="~/images/upload-icon.png" alt="Upload Icon" title="@ParcelrateResources.Resources.Upload_CSV_File">
            </div>
        </label>
        <div id="divUpload" style="display:none;">
            <input type="file" accept=".csv" name="files" id="files" />
        </div>
    </div>
    <div class="or-circle">@ParcelrateResources.Resources.Or</div>
    <a href="javascript:void(0);" title="@ParcelrateResources.Resources.Download_Sample_CSV" class="sample-scv" onclick="downloadSampleCSV();">@ParcelrateResources.Resources.Download_Sample_CSV</a>
</div>
<div class="con-padding minHeight100">
    <form method="post" asp-controller="Address" asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-12">
                                <input class="form-control" tabindex="1" type="text" maxlength="50" placeholder="@ParcelrateResources.Resources.Customer_ID*" asp-for="CustomerID">
                            </div>
                            <div class="col-md-12">
                                <span asp-validation-for="CustomerID" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-7">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group custom-select">
                                                <select class="form-control" tabindex="7" id="ddlCountry" asp-for="CountryId" asp-items="@(new SelectList(ViewBag.CountryList,"ID","Name"))" onchange="return getCountryData(this);">
                                                    <option disabled selected>@ParcelrateResources.Resources.Select</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <span asp-validation-for="CountryId" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <input id="txtCountryCode" class="form-control" type="text" placeholder="@ParcelrateResources.Resources.Country_Code" asp-for="CountryCode" disabled />
                                        <input type="hidden" id="CountryCode" asp-for="CountryCode" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <input class="form-control" tabindex="2" type="text" maxlength="50" placeholder="@ParcelrateResources.Resources.Company" asp-for="Company" />
                        <span asp-validation-for="Company" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <input class="form-control" tabindex="8" type="text" maxlength="10" placeholder="@ParcelrateResources.Resources.Postal_Code*" asp-for="PostalCode" />
                        <span asp-validation-for="PostalCode" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <input class="form-control" tabindex="3" type="text" maxlength="50" placeholder="@ParcelrateResources.Resources.First_Name" asp-for="FirstName" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <input class="form-control" tabindex="9" type="text" maxlength="50" placeholder="@ParcelrateResources.Resources.City*" asp-for="City" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                <input class="form-control" tabindex="4" type="text" maxlength="50" placeholder="@ParcelrateResources.Resources.Last_Name*" asp-for="LastName" />
                            </div>
                            <div class="col-md-12">
                                <span asp-validation-for="LastName" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-12">
                                <input id="txtPhonePrefix" class="form-control phone-prefix" type="text" placeholder="@ParcelrateResources.Resources.Phone_Prefix" asp-for="PhonePrefix" disabled />
                                <input class="form-control phone-number" tabindex="10" type="text" maxlength="15" placeholder="@ParcelrateResources.Resources.Phone_Number*" asp-for="PhoneNo" />
                                <input type="hidden" id="PhonePrefix" asp-for="PhonePrefix" />
                            </div>
                            <div class="col-md-12">
                                <div style="margin-left: 30%;">
                                    <span asp-validation-for="PhoneNo" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <input class="form-control" tabindex="5" type="text" maxlength="200" placeholder="@ParcelrateResources.Resources.Street*" asp-for="Address1" />
                        <span asp-validation-for="Address1" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <input class="form-control" tabindex="11" type="text" maxlength="50" placeholder="@ParcelrateResources.Resources.Email*" asp-for="Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <input class="form-control" tabindex="6" type="text" maxlength="7" placeholder="@ParcelrateResources.Resources.House_Number*" asp-for="Address2" />
                        <span asp-validation-for="Address2" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @if (Model.IsDefault)
                        {
                            <div class="checkbox">
                                <label>
                                    @Html.CheckBoxFor(m => m.IsPickupOrder, new { title = ParcelrateResources.Resources.Pickup_Order })
                                    <span class="cr"><i class="cr-icon glyphicon glyphicon-ok"></i></span>@ParcelrateResources.Resources.Pickup_Order
                                </label>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">

                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="pull-right">
                            <input class="btn submi-btn" tabindex="12" type="submit" name="submit-login" value="@ParcelrateResources.Resources.Save" title="@ParcelrateResources.Resources.Save" />&nbsp;
                            <a class="btn cancel-btn" tabindex="13" href="~/Address/Index" title="@ParcelrateResources.Resources.Cancel">@ParcelrateResources.Resources.Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="con-padding footer-links">
    <ul class="footer-listing pull-right">
        <li>
            <a>Copyright &copy; Parcel Kiosk Limited</a>
        </li>
    </ul>
</div>

@section scripts {
    <script>
        $(function () {
            $(".left-sxn ul li a").click(function () {
                getHasChanges($(this).attr("href"));
                return false;
            });
            $("#aLogOut").click(function () {
                getHasChanges($(this).attr("href"));
                return false;
            });
            if ('@ViewBag.IsSuccess') {
                ShowAddressMessagePopup('@ParcelrateResources.Resources.Address_Saved');
            }
             else if ('@ViewBag.ErrorMessage' != '')
                showMessagePopup('@Html.Raw(ViewBag.ErrorMessage)');
        });
    </script>
}

Parcelrate/Views/Address/Index.cshtml
@using ReflectionIT.Mvc.Paging
@model PagingList<ParcelrateEntities.Models.Address>
@using ParcelrateUtilities

@addTagHelper *, ReflectionIT.Mvc.Paging

@{
    ViewData["Title"] = ParcelrateResources.Resources.Addresses;
    ViewBag.CurrentPage = "Addresses";
}
<div class="con-padding shipmant-heading">
    <div class="col-md-12">
        <h1>@ParcelrateResources.Resources.Saved_Addresses</h1>
        <a asp-action="Create" class="pull-right add-new-address"><span>+</span> @ParcelrateResources.Resources.New</a>
    </div>
</div>

<div class="con-padding minHeight100">
    <div class="col-md-12">
        <div class="row" style="margin-top:10px;">
            <div class="col-md-4 pull-right">
                <form method="get">
                    <div class="input-group">
                        <input class="form-control search-input" id="filter" type="text" name="filter" maxlength="50" placeholder="@ParcelrateResources.Resources.Search_By_Name" value="@Model.RouteValue[Constants.Filter]" /> @*onkeyup="searchAddress();"*@
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit" title="@ParcelrateResources.Resources.Search">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            @if (Model != null && Model.Count > 0)
            {
                @foreach (var item in Model)
                {

                    <div class="col-lg-6">
                        <div class="address-con">
                            <div class="address-head">
                                @if (item.IsDefault)
                                {
                                    <p class="ellipsis">@ParcelrateResources.Resources.Default_Address (@(item.IsPickupOrder ? ParcelrateResources.Resources.Pickup_Ordered : ParcelrateResources.Resources.Autopickup))</p>
                                }
                                else
                                {
                                    <p class="ellipsis" title="@item.CustomerId">@ParcelrateResources.Resources.Customer_ID: @item.CustomerId</p>
                                }
                                <p class="customer-name ellipsis" title="@item.FirstName&nbsp;@item.LastName">@item.FirstName&nbsp;@item.LastName</p>
                                <div class="address-icons">
                                    <a asp-action="Edit" asp-route-id="@item.Id"><img src="~/images/edit-icon.png" title="@ParcelrateResources.Resources.Edit" alt="@ParcelrateResources.Resources.Edit"></a>
                                    <a href="javascript:void(0);" onclick="openDeletePopup(@item.Id)"><img src="~/images/delete-icon.png" title="@ParcelrateResources.Resources.Delete" alt="@ParcelrateResources.Resources.Delete"></a>
                                </div>
                            </div>
                            <div class="address-body">
                                <p class="ellipsis" title="@item.Address1,&nbsp;@item.Address2">
                                    <img src="~/images/adress-icon.png" alt="Address"> @item.Address1,&nbsp;@item.Address2,<br>
                                    @item.City,&nbsp;@item.PostalCode<br>
                                    @item.Country?.Name&nbsp;@item.Country?.Code
                                </p>
                                <p class="ellipsis" title="@item.FirstName&nbsp;@item.LastName"><img src="~/images/user-icon.png" alt="User">@item.FirstName&nbsp;@item.LastName</p>
                                <p><img src="~/images/phone-icon.png" alt="User"> +@item.PhonePrefix&nbsp;@item.PhoneNumber</p>
                                <p class="ellipsis"><img src="~/images/mail-icon.png" alt="User"> <a href="mailto:@item.Email" title="@item.Email">@item.Email</a></p>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="col-lg-12">
                    <div class="address-head" style="min-height: 70px;margin-top: 50px;">
                        <p style="font-size: 20px;font-weight: bold;text-align: center;padding-left: 0px;margin-top: 15px;color: #bdb8b8;font-family: 'mulilight';">@ParcelrateResources.Resources.No_Records_Found</p>
                    </div>
                </div>
            }

        </div>
        <div class="clearfix"></div>
    </div>
    <nav aria-label="Addresses" class="pull-right">
        <vc:pager paging-list="@Model" />
    </nav>

    <div class="con-padding footer-links">
        <ul class="footer-listing pull-right">
            <li>
                <a>Copyright &copy; Parcel Kiosk Limited</a>
            </li>
        </ul>
    </div>


</div>

<div class="confirmation-layout" id="divDeletePopup">
    <div class="confirmation-inner-layout">
        <h3>@ParcelrateResources.Resources.Confirmation</h3>
        <p>@ParcelrateResources.Resources.Delete_Confirmation_Message</p>
        <div class="pull-right">
            <button class="confirm-button active" type="button" onclick="deleteAddress();">@ParcelrateResources.Resources.Yes</button>
            <button class="confirm-button" type="button" onclick="closeDeletePopup();">@ParcelrateResources.Resources.No</button>
        </div>
        <div class="close-btn"><a href="javascript:void(0);" title="@ParcelrateResources.Resources.Close" onclick="closeDeletePopup();"><img src="~/images/close.png" alt="@ParcelrateResources.Resources.Close"></a></div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">


        var selectedAddressId = 0;
        function openDeletePopup(id) {
            selectedAddressId = id;
            $("#divDeletePopup").slideDown();
            $("body").addClass('layout-hide');
        }

        function closeDeletePopup() {
            selectedAddressId = 0;
            $("#divDeletePopup").slideUp();
            $("body").removeClass('layout-hide');
        }

        function deleteAddress() {
            showLoader();
            $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Delete")',
                    dataType: 'json',
                    data: { id: selectedAddressId },
                    async: false,
                    success: function (response) {
                        if (response) {
                            closeDeletePopup();
                            setTimeout(function () {
                                if (response.isSuccess) {
                                    ShowAddressMessagePopup(response.message);
                                }
                                else
                                    showMessagePopup(response.error);
                            }, 500);
                        }
                    },
                    error: function (ex) {
                        closeDeletePopup();
                        showMessagePopup('@Html.Raw(ParcelrateResources.Resources.ErrorMessage)');
                    }
            });
            hideLoader();
        }

        function searchAddress() {
            var searchString = $("#filter").val();
            window.location.href = '/Address?filter=' + searchString +'&page=@Model.RouteValue["page"]'
        }
    </script>
}